### ISSUE TITLE
Updates to Launch 2023

### ISSUE THREAD

**Issue by MattClarkson** [UCL/MPHY0026#64]

**Comment by tdowrick** [comment]
# Testing on Windows

## 17.4.1 Camera Calibration
- [x] Working, with one commit needed to update a command (I will push this).
- [ ] The `bardVideoCalibrationChecker` app is continously printing a `print("Failed to detect points")` which means it very hard to actually see the desired output of the app. I have traced this to https://github.com/SciKit-Surgery/scikit-surgerycalibration/blob/c979634ae575178490876972cace70b28e6a7879/sksurgerycalibration/ui/video_calibration_checker_app.py#L132 but this will need a change in scikit-surgerycalibration and scikit-surgerybard to fix.

## 17.4.2 Make your own pointer
- [x] Not currently working for me - no overlay showing on the Aruco marker. Will investigate further.

## 17.4.3 FRED
Seems fine to me, web app so unlikely to be any issues since last time.

## 17.4.4 AR Overlay
- [x] Made one update to the code to work with latest BARD.

All changes are currently on https://github.com/UCL/MPHY0026/tree/64-tom

@thompson318 any thoughts on the issues with camera calibration/pointer apps?

I can also give it a run through on my Ubuntu laptop.

**Comment by tdowrick** [comment]
Other thought - scikit-surgerpclcpp and opencvcpp are dependencies for MPHY0026 but as far as I can tell they aren't used anywhere.

If we can remove these it may make it easier to run with different versions of Python, as currently they only have wheels up to 3.7.

**Comment by tdowrick** [comment]
# Ubuntu

Camera Calibraiton, Pointer, and FRED same as above.

AR Overlay not working, related to the issue with VTK windows on Ubuntu?

**Comment by thompson318** [comment]
> Other thought - scikit-surgerpclcpp and opencvcpp are ....

They were used in surgery-calibration, but should have been removed now, so should be removed from MPHY0026

**Comment by thompson318** [comment]
> Not currently working for me - no overlay showing on the Aruco marker. Will investigate further.

I suspect this is because the configuration file described in the docs is out of date. Did you copy and paste from the docs? It needs to updated like this https://github.com/UCL/MPHY0026/commit/b7de62bfe3dd215af6191cb4150163ea91091389, see issue #62. I can do that today or tomorrow.

**Comment by thompson318** [comment]
> AR Overlay not working, related to the issue with VTK windows on Ubuntu

I've created a version of BARD that works for me (ubuntu) with VTK > 9. It's here https://github.com/SciKit-Surgery/scikit-surgerybard/tree/101-skutils. It needs sksurgeryutils>1.2.1 and takes the Start and Initialize commands out of the constructor for vtk_overlay window. @tdowrick Can you test it on windows? @MattClarkson and mac?

**Comment by thompson318** [comment]
I've fixed the pivot calibration documentation. Fix is here: https://github.com/UCL/MPHY0026/tree/62-fix-config. There's a quite a few  pylint problems that should be resolved first (https://github.com/UCL/MPHY0026/actions)

**Comment by tdowrick** [comment]
> I've fixed the pivot calibration documentation. Fix is here: https://github.com/UCL/MPHY0026/tree/62-fix-config. There's a quite a few pylint problems that should be resolved first (https://github.com/UCL/MPHY0026/actions)

Yes this works for me now.

**Comment by tdowrick** [comment]
I have fixed linting errors and merged mine and Steve's recent changes to master.

**Comment by tdowrick** [comment]
> > AR Overlay not working, related to the issue with VTK windows on Ubuntu
> 
> I've created a version of BARD that works for me (ubuntu) with VTK > 9. It's here https://github.com/SciKit-Surgery/scikit-surgerybard/tree/101-skutils. It needs sksurgeryutils>1.2.1 and takes the Start and Initialize commands out of the constructor for vtk_overlay window. @tdowrick Can you test it on windows? @MattClarkson and mac?

Works for me on Windows

**Comment by thompson318** [comment]
I've updated BARD to use an up to date version of videocalibration videocalibrationchecker from sksutils. I think the spamming should be fixed now.

**Comment by tdowrick** [comment]
There were a few conflicting requirements in MPHY0026 and the new BARD, but I have resolved these now and the issues seems to be resolved now.

I don't think there are any more changes to make, so will close now.
